# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / Twitter
nav:
- Home: index.md
- Introduction: introduction.md
- Account Setup: twitter-account-setup.md
- Sending Tweets: sending-tweets.md
- Mobile Notifications: twitter-mobile-notifications.md
- Authentication: authentication.md
- Twitter API: twitter-api.md
#- Install MkDocs: install.md
# //TODO: Add Resources
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  Copyright Open Water Foundation
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics:
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# ------------------------------------------------
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-mkdocs
site_author:  Open Water Foundation
site_description:  Open Water Foundation Learn Twitter
# ------------------------------------------------
# Use Material theme:
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon: 'images/OWF-Logo-Favicon-32x32.png'
